runtime: go113

main: ./cmd/server

vpc_access_connector:
  name: "projects/convo-api/locations/us-central1/connectors/convo-internal"

handlers:
  - url: .*
    script: auto
    secure: always

instance_class: F2

inbound_services:
  - warmup

automatic_scaling:
  max_instances: 2
  min_instances: 1
  max_concurrent_requests: 80
