version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATASTORE_PROJECT_ID=convo-api
      - DATASTORE_LISTEN_ADDRESS=datastore:8081
      - DATASTORE_DATASET=convo-api
      - DATASTORE_EMULATOR_HOST=datastore:8081
      - DATASTORE_EMULATOR_HOST_PATH=datastore:8081/datastore
      - DATASTORE_HOST=http://datastore:8081
    env_file:
      - ./.env
    volumes:
      - .:/var/www
    links:
      - datastore
      - elasticsearch
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=convo-api
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    command: --consistency=1.0
    ports:
      - "8081"
  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - "9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
