version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11.6-stretch

    steps:

      - run:
          name: install gcloud sdk
          command: |
            CLOUD_SDK_REPO="cloud-sdk-$(grep VERSION_CODENAME /etc/os-release | cut -d '=' -f 2)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk

      - run:
          name: authenticate gcloud sdk
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - checkout

      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "go.sum" }}
      - run: 
          name: retrieve go dependencies
          command: go get
      - save_cache:
          key: pkg-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

      - run:
          name: starting datastore emulator
          command: gcloud beta emulators datastore start
          background: true

      - run:
          name: set datastore environment variables
          command: |
            IFS=''
            for line in $(gcloud beta emulators datastore env-init); do
              echo $line >> $BASH_ENV
            done

      - run:
          name: run tests
          command: cd tests && go test

  deploy:
    docker:
      - image: circleci/golang:1.11.6-stretch

    steps:

      - run:
          name: install gcloud sdk
          command: |
            CLOUD_SDK_REPO="cloud-sdk-$(grep VERSION_CODENAME /etc/os-release | cut -d '=' -f 2)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk

      - run:
          name: authenticate gcloud sdk
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: install redoc-cli
          command: npm i -g redoc-cli

      - checkout
        
      - restore_cache:
          keys:
            - pkg-cache
      - run: 
          name: retrieve go dependencies
          command: go get
      - save_cache:
          key: pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: generate docs
          command: |
            mkdir -p main/static
            redoc-cli bundle swagger.yaml
            mv redoc-static.html main/static/index.html

      - deploy:
          command: gcloud app deploy main/app.yaml

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

