version: 2
jobs:
  test:
    docker:
      - image: hiconvo/docker:ci
        environment:
          DATASTORE_PROJECT_ID: convo-api
          DATASTORE_LISTEN_ADDRESS: localhost:8081
          DATASTORE_DATASET: convo-api
          DATASTORE_EMULATOR_HOST: localhost:8081
          DATASTORE_EMULATOR_HOST_PATH: localhost:8081/datastore
          DATASTORE_HOST: http://localhost:8081
          ELASTICSEARCH_HOST: localhost

      - image: singularities/datastore-emulator
        command: --no-store-on-disk --consistency=1.0
        environment:
          DATASTORE_PROJECT_ID: convo-api
          DATASTORE_LISTEN_ADDRESS: localhost:8081

      - image: elasticsearch:7.1.1
        environment:
          cluster.name: docker-cluster
          bootstrap.memory_lock: "true"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          discovery.type: single-node

    steps:

      - checkout

      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "go.sum" }}
      - run: 
          name: retrieve go dependencies
          command: go get

      - run:
          name: run tests
          command: |
            go test ./...

      - save_cache:
          key: pkg-cache-{{ checksum "go.sum" }}
          paths:
            - "/usr/local/go/src"

  deploy:
    docker:
      - image: hiconvo/docker:ci

    steps:

      - run:
          name: authenticate gcloud sdk
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: install redoc-cli
          command: npm i -g redoc-cli

      - checkout

      - run:
          name: generate docs
          command: |
            mkdir -p static
            redoc-cli bundle swagger.yaml
            mv redoc-static.html static/index.html

      - deploy:
          command: gcloud beta -q app deploy app.yaml

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

